# Generated by Django 5.2.3 on 2025-06-15 22:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('especie', models.CharField(max_length=50)),
                ('raza', models.CharField(max_length=50)),
                ('sexo', models.CharField(max_length=10)),
                ('fecha_nacimiento', models.DateField()),
                ('microchip_tatuaje', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AtencionMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_atencion', models.DateTimeField(auto_now_add=True)),
                ('tipo_atencion', models.CharField(choices=[('Clínica', 'Clínica Veterinaria'), ('Club', 'Club Entre Patitas')], max_length=10)),
                ('motivo_consulta', models.TextField(help_text='Debe tener un mínimo de 10 caracteres.')),
                ('anamnesis', models.TextField(verbose_name='Anamnesis (antecedentes previos y actuales)')),
                ('diagnostico', models.TextField()),
                ('tratamiento', models.TextField()),
                ('veterinario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChequeoFisico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura', models.DecimalField(decimal_places=2, max_digits=4)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('condicion_corporal', models.CharField(max_length=100)),
                ('anotaciones', models.TextField(blank=True, null=True)),
                ('atencion_medica', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chequeo', to='gestion.atencionmedica')),
            ],
        ),
        migrations.CreateModel(
            name='FichaClinica',
            fields=[
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='gestion.paciente')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_modificacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Procedimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Cirugía', 'Cirugía'), ('Examen', 'Examen'), ('Hospitalización', 'Hospitalización')], max_length=20)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('atencion_medica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedimientos', to='gestion.atencionmedica')),
            ],
        ),
        migrations.AddField(
            model_name='paciente',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacientes', to='gestion.tutor'),
        ),
        migrations.AddField(
            model_name='atencionmedica',
            name='ficha_clinica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atenciones', to='gestion.fichaclinica'),
        ),
    ]
