# Generated by Django 5.2.3 on 2025-06-16 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atencionmedica',
            name='jaula_numero',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Número de Jaula'),
        ),
        migrations.AddField(
            model_name='atencionmedica',
            name='notas_hospitalizacion',
            field=models.TextField(blank=True, help_text='Notas específicas de la hospitalización', null=True),
        ),
    ]
