# Generated by Django 5.2.3 on 2025-06-16 02:15

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_atencionmedica_jaula_numero_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalAtencionMedica',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('fecha_atencion', models.DateTimeField(blank=True, editable=False)),
                ('tipo_atencion', models.CharField(choices=[('Clínica', 'Clínica Veterinaria'), ('Club', 'Club Entre Patitas')], max_length=10)),
                ('motivo_consulta', models.TextField(help_text='Debe tener un mínimo de 10 caracteres.')),
                ('anamnesis', models.TextField(verbose_name='Anamnesis (antecedentes previos y actuales)')),
                ('diagnostico', models.TextField()),
                ('tratamiento', models.TextField()),
                ('notas_hospitalizacion', models.TextField(blank=True, help_text='Notas específicas de la hospitalización', null=True)),
                ('jaula_numero', models.CharField(blank=True, max_length=10, null=True, verbose_name='Número de Jaula')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('ficha_clinica', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gestion.fichaclinica')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('veterinario', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical atencion medica',
                'verbose_name_plural': 'historical atencion medicas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
