# Generated by Django 5.2.3 on 2025-08-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_documentoadjunto'),
    ]

    operations = [
        migrations.AddField(
            model_name='atencionmedica',
            name='esta_cerrada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalatencionmedica',
            name='esta_cerrada',
            field=models.BooleanField(default=False),
        ),
    ]
