# Generated by Django 5.2.3 on 2025-08-26 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_atencionmedica_esta_cerrada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atencionmedica',
            name='tipo_visita',
            field=models.CharField(choices=[('Consulta', 'Consulta Básica'), ('Urgencia', 'Urgencia'), ('Domicilio', 'Visita a Domicilio')], default='Consulta', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalatencionmedica',
            name='tipo_visita',
            field=models.CharField(choices=[('Consulta', 'Consulta Básica'), ('Urgencia', 'Urgencia'), ('Domicilio', 'Visita a Domicilio')], default='Consulta', max_length=20),
            preserve_default=False,
        ),
    ]
