# Generated by Django 5.2.5 on 2025-08-26 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_atencionmedica_tipo_visita_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atencionmedica',
            name='estado_emocional',
            field=models.CharField(blank=True, choices=[('Tranquilo', 'Tranquilo'), ('Nervioso', 'Nervioso'), ('Agresivo', 'Agresivo')], max_length=20, null=True, verbose_name='Comportamiento del Paciente'),
        ),
        migrations.AddField(
            model_name='historicalatencionmedica',
            name='estado_emocional',
            field=models.CharField(blank=True, choices=[('Tranquilo', 'Tranquilo'), ('Nervioso', 'Nervioso'), ('Agresivo', 'Agresivo')], max_length=20, null=True, verbose_name='Comportamiento del Paciente'),
        ),
    ]
