# Generated by Django 5.2.5 on 2025-08-26 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_atencionmedica_estado_emocional_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedimiento',
            name='tipo_cirugia',
            field=models.CharField(blank=True, choices=[('Urgencia', 'Urgencia'), ('Programada', 'Programada')], max_length=20, null=True, verbose_name='Tipo de Cirugía'),
        ),
    ]
