# Generated by Django 5.2.5 on 2025-09-08 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_diagnostico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('costo', models.DecimalField(decimal_places=2, help_text='Costo por unidad del insumo', max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='InsumoUtilizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('costo_total', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('atencion_medica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos_utilizados', to='gestion.atencionmedica')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.insumo')),
            ],
        ),
    ]
