# Generated by Django 5.2.5 on 2025-09-09 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_insumo_insumoutilizado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atencionmedica',
            name='diagnostico',
        ),
        migrations.RemoveField(
            model_name='historicalatencionmedica',
            name='diagnostico',
        ),
        migrations.AddField(
            model_name='atencionmedica',
            name='diagnosticos',
            field=models.ManyToManyField(blank=True, related_name='atenciones', to='gestion.diagnostico', verbose_name='Diagnósticos'),
        ),
        migrations.AddField(
            model_name='atencionmedica',
            name='prediagnosticos',
            field=models.ManyToManyField(blank=True, related_name='atenciones_prediagnostico', to='gestion.diagnostico', verbose_name='Prediagnósticos (Opcional)'),
        ),
    ]
