# Generated by Django 5.2.5 on 2025-09-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0012_atencionmedica_fecha_egreso_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atencionmedica',
            name='esta_cerrada',
        ),
        migrations.RemoveField(
            model_name='historicalatencionmedica',
            name='esta_cerrada',
        ),
        migrations.AddField(
            model_name='atencionmedica',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Completa', 'Completa'), ('Cerrada', 'Cerrada (No se puede editar)')], default='Pendiente', max_length=20, verbose_name='Estado de la Ficha'),
        ),
        migrations.AddField(
            model_name='historicalatencionmedica',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Completa', 'Completa'), ('Cerrada', 'Cerrada (No se puede editar)')], default='Pendiente', max_length=20, verbose_name='Estado de la Ficha'),
        ),
    ]
