# Generated by Django 5.2.5 on 2025-09-09 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0013_remove_atencionmedica_esta_cerrada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atencionmedica',
            name='esta_cerrada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalatencionmedica',
            name='esta_cerrada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='atencionmedica',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Completa', 'Completa')], default='Pendiente', max_length=20, verbose_name='Estado de la Ficha'),
        ),
        migrations.AlterField(
            model_name='historicalatencionmedica',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Completa', 'Completa')], default='Pendiente', max_length=20, verbose_name='Estado de la Ficha'),
        ),
    ]
