# Generated by Django 5.2.5 on 2025-09-09 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0014_atencionmedica_esta_cerrada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripcion de la alerta y qué implica.', null=True)),
                ('severidad', models.CharField(choices=[('Alta', 'Alta (Roja)'), ('Media', 'Media (Naranja)'), ('Baja', 'Baja (Azul)')], default='Baja', max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='paciente',
            name='alertas',
            field=models.ManyToManyField(blank=True, to='gestion.alertaclinica', verbose_name='Alertas Clinicas'),
        ),
    ]
