# Generated by Django 5.2.5 on 2025-09-10 15:39

from django.db import migrations

ALERTAS_INICIALES = [
    # Categoría: Alergia
    {"nombre": "Alergia a la Penicilina", "descripcion": "No administrar amoxicilina ni derivados.", "severidad": "Alta", "categoria": "Alergia"},
    {"nombre": "Alergia al Pollo", "descripcion": "Evitar alimentos y premios que contengan pollo.", "severidad": "Media", "categoria": "Alergia"},

    # Categoría: Condición Crónica
    {"nombre": "Condición Cardíaca", "descripcion": "Paciente con soplo. Evitar sedantes con efectos depresores.", "severidad": "Alta", "categoria": "Condición Crónica"},
    {"nombre": "Insuficiencia Renal Crónica", "descripcion": "Requiere dieta renal y monitoreo de fluidos.", "severidad": "Alta", "categoria": "Condición Crónica"},
    {"nombre": "Epilepsia / Convulsiones", "descripcion": "Paciente en tratamiento con fenobarbital.", "severidad": "Media", "categoria": "Condición Crónica"},

    # Categoría: Comportamiento
    {"nombre": "Agresivo con extraños", "descripcion": "Acercarse con precaución. Considerar uso de bozal.", "severidad": "Media", "categoria": "Comportamiento"},
    {"nombre": "Ansiedad por separación", "descripcion": "Puede mostrar signos de estrés si se le deja solo.", "severidad": "Baja", "categoria": "Comportamiento"},
    
    # Categoría: Manejo Específico
    {"nombre": "Requiere Bozal", "descripcion": "Bozal necesario para toda manipulación y examinación.", "severidad": "Baja", "categoria": "Manejo Específico"},
]

def cargar_alertas(apps, schema_editor):
    AlertaClinica = apps.get_model('gestion', 'AlertaClinica')
    for alerta_data in ALERTAS_INICIALES:
        AlertaClinica.objects.get_or_create(nombre=alerta_data['nombre'], defaults=alerta_data)

class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0016_alertaclinica_categoria'), 
    ]

    operations = [
        migrations.RunPython(cargar_alertas),
    ]