# Generated by Django 5.2.5 on 2025-09-11 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0017_cargar_alertas_iniciales'),
    ]

    operations = [
        migrations.AddField(
            model_name='atencionmedica',
            name='observaciones_sensibles',
            field=models.TextField(blank=True, help_text='Estas notas no serán visibles para el tutor.', null=True, verbose_name='Observaciones Médicas Sensibles (Solo personal)'),
        ),
        migrations.AddField(
            model_name='historicalatencionmedica',
            name='observaciones_sensibles',
            field=models.TextField(blank=True, help_text='Estas notas no serán visibles para el tutor.', null=True, verbose_name='Observaciones Médicas Sensibles (Solo personal)'),
        ),
    ]
