# Generated by Django 5.2.5 on 2025-09-11 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0020_solicituddatospersonales'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltutor',
            name='datos_bloqueados',
            field=models.BooleanField(default=False, verbose_name='Datos Bloqueados (No editar)'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='datos_bloqueados',
            field=models.BooleanField(default=False, verbose_name='Datos Bloqueados (No editar)'),
        ),
    ]
