# Generated by Django 5.2.5 on 2025-09-12 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0021_historicaltutor_datos_bloqueados_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_pacientes/', verbose_name='Fotografía del Paciente'),
        ),
    ]
