# Generated by Django 5.2.5 on 2025-09-12 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0024_cita'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='es_especialista',
            field=models.BooleanField(default=False, verbose_name='¿Es cita con especialista?'),
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('metodo_pago', models.CharField(default='No especificado', max_length=50)),
                ('notas', models.TextField(blank=True, null=True)),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='gestion.cita')),
            ],
        ),
    ]
