# Generated by Django 5.2.5 on 2025-09-12 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0025_cita_es_especialista_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='es_domicilio',
            field=models.BooleanField(default=False, verbose_name='¿Es visita a domicilio?'),
        ),
    ]
