# Generated by Django 5.2.5 on 2025-09-13 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0026_cita_es_domicilio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('especie_objetivo', models.CharField(help_text='Ej: Canino, Felino', max_length=50)),
                ('dosis_necesarias', models.PositiveIntegerField(default=1)),
                ('frecuencia_refuerzo_dias', models.PositiveIntegerField(help_text='Días hasta el próximo refuerzo (ej: 365 para anual)')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroVacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_aplicacion', models.DateField()),
                ('proxima_dosis_fecha', models.DateField(blank=True, editable=False, null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_vacunas', to='gestion.paciente')),
                ('vacuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.vacuna')),
            ],
        ),
    ]
