# Generated by Django 5.2.5 on 2025-09-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_atencionmedica_diagnostico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atencionmedica',
            name='fecha_egreso',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Egreso'),
        ),
        migrations.AddField(
            model_name='historicalatencionmedica',
            name='fecha_egreso',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Egreso'),
        ),
    ]
