# Generated by Django 5.2.5 on 2025-09-10 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alertaclinica_paciente_alertas'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertaclinica',
            name='categoria',
            field=models.CharField(choices=[('Alergia', 'Alergia'), ('Condición Crónica', 'Condición Crónica'), ('Comportamiento', 'Comportamiento'), ('Manejo Específico', 'Manejo Específico')], default='Manejo Específico', max_length=50),
        ),
    ]
