# Generated by Django 5.2.5 on 2025-09-11 22:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_historicaltutor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudDatosPersonales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_solicitud', models.CharField(choices=[('Acceso', 'Solicitud de Acceso'), ('Modificación', 'Solicitud de Modificación'), ('Cancelación', 'Solicitud de Cancelación'), ('Bloqueo', 'Solicitud de Bloqueo')], max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobada', 'Aprobada'), ('Rechazada', 'Rechazada')], default='Pendiente', max_length=20)),
                ('resolucion', models.TextField(blank=True, help_text="Detalles de la resolución de la solicitud (ej: 'Se enviaron los datos por correo el DD/MM/AAAA').", null=True)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='app.tutor')),
                ('usuario_responsable', models.ForeignKey(help_text='Usuario que gestionó la solicitud.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
