# Generated by Django 5.2.5 on 2025-09-13 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_vacuna_registrovacuna'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='tutor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='app.tutor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pago',
            name='cita',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='app.cita'),
        ),
    ]
