# Generated by Django 5.2.5 on 2025-09-13 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_pago_tutor_alter_pago_cita'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador'), ('VET', 'Veterinario'), ('ESP', 'Veterinario Especialista'), ('SECRETARIA', 'Secretaría'), ('TUTOR', 'Tutor')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
