# Generated by Django 5.2.5 on 2025-09-28 23:14

from django.db import migrations

DIAGNOSTICOS_INICIALES = [
    "Gastroenteritis",
    "Otitis",
    "Dermatitis alérgica",
    "Insuficiencia renal",
    "Conjuntivitis",
    "Parvovirus",
    "Moquillo (Distemper)",
    "Traumatismo",
    "Cistitis",
    "Alergia Alimentaria",
    "Control Sano",
    "Otro",
]

def cargar_diagnosticos(apps, schema_editor):
    Diagnostico = apps.get_model('app', 'Diagnostico')
    for nombre_diagnostico in DIAGNOSTICOS_INICIALES:
        Diagnostico.objects.get_or_create(nombre=nombre_diagnostico)

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_perfil'), 
    ]

    operations = [
        migrations.RunPython(cargar_diagnosticos),
    ]