# Generated by Django 5.2.5 on 2025-10-19 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_cargar_diagnosticos_iniciales'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='canal_notificacion_preferido',
            field=models.CharField(choices=[('EMAIL', 'Correo Electrónico'), ('WHATSAPP', 'WhatsApp'), ('NONE', 'No recibir')], default='EMAIL', max_length=10, verbose_name='Canal de notificación preferido'),
        ),
    ]
