# Generated by Django 5.2.5 on 2025-10-21 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_mensaje'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('prescripcion', models.TextField(verbose_name='Prescripción')),
                ('impresa', models.BooleanField(default=False, verbose_name='¿Impresa/Generada?')),
                ('atencion_medica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to='app.atencionmedica')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
