# Generated by Django 5.2.5 on 2025-10-29 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_receta'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='firma',
            field=models.ImageField(blank=True, null=True, upload_to='firmas/', verbose_name='Imagen de Firma/Timbre'),
        ),
    ]
