# Generated by Django 5.2.5 on 2025-11-18 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_perfil_firma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atencionmedica',
            name='diagnosticos',
        ),
        migrations.RemoveField(
            model_name='atencionmedica',
            name='prediagnosticos',
        ),
        migrations.RemoveField(
            model_name='atencionmedica',
            name='tratamiento',
        ),
        migrations.RemoveField(
            model_name='historicalatencionmedica',
            name='tratamiento',
        ),
        migrations.AddField(
            model_name='atencionmedica',
            name='diagnostico',
            field=models.TextField(blank=True, help_text='Ingrese el diagnóstico final.', verbose_name='Diagnóstico'),
        ),
        migrations.AddField(
            model_name='atencionmedica',
            name='lugar_atencion',
            field=models.CharField(choices=[('BILBAO', 'Sede Bilbao'), ('YANEZ', 'Sede Eliodoro Yáñez'), ('DOMICILIO', 'Domicilio')], default='BILBAO', max_length=20, verbose_name='Sede / Lugar'),
        ),
        migrations.AddField(
            model_name='atencionmedica',
            name='prediagnostico',
            field=models.TextField(blank=True, help_text='Ingrese el prediagnóstico aquí.', verbose_name='Prediagnóstico'),
        ),
        migrations.AddField(
            model_name='chequeofisico',
            name='frecuencia_cardiaca',
            field=models.CharField(blank=True, max_length=50, verbose_name='Frecuencia Cardíaca (FC)'),
        ),
        migrations.AddField(
            model_name='chequeofisico',
            name='frecuencia_respiratoria',
            field=models.CharField(blank=True, max_length=50, verbose_name='Frecuencia Respiratoria (FR)'),
        ),
        migrations.AddField(
            model_name='chequeofisico',
            name='mucosas',
            field=models.CharField(blank=True, max_length=100, verbose_name='Mucosas'),
        ),
        migrations.AddField(
            model_name='chequeofisico',
            name='tllc',
            field=models.CharField(blank=True, max_length=50, verbose_name='TLLC'),
        ),
        migrations.AddField(
            model_name='historicalatencionmedica',
            name='diagnostico',
            field=models.TextField(blank=True, help_text='Ingrese el diagnóstico final.', verbose_name='Diagnóstico'),
        ),
        migrations.AddField(
            model_name='historicalatencionmedica',
            name='lugar_atencion',
            field=models.CharField(choices=[('BILBAO', 'Sede Bilbao'), ('YANEZ', 'Sede Eliodoro Yáñez'), ('DOMICILIO', 'Domicilio')], default='BILBAO', max_length=20, verbose_name='Sede / Lugar'),
        ),
        migrations.AddField(
            model_name='historicalatencionmedica',
            name='prediagnostico',
            field=models.TextField(blank=True, help_text='Ingrese el prediagnóstico aquí.', verbose_name='Prediagnóstico'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='estado_reproductivo',
            field=models.CharField(choices=[('Entero', 'Entero'), ('Castrado', 'Castrado/Esterilizado')], default='Entero', max_length=20, verbose_name='Estado Reproductivo'),
        ),
        migrations.AlterField(
            model_name='chequeofisico',
            name='anotaciones',
            field=models.TextField(blank=True, default='', verbose_name='Hallazgos / Anotaciones'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chequeofisico',
            name='condicion_corporal',
            field=models.CharField(max_length=50, verbose_name='Condición Corporal'),
        ),
        migrations.AlterField(
            model_name='chequeofisico',
            name='peso',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Peso (Kg)'),
        ),
        migrations.AlterField(
            model_name='chequeofisico',
            name='temperatura',
            field=models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Temperatura (°C)'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(choices=[('Macho', 'Macho'), ('Hembra', 'Hembra')], max_length=10),
        ),
    ]
