# Generated by Django 5.2.5 on 2025-11-21 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_remove_atencionmedica_diagnosticos_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Diagnostico',
        ),
        migrations.AddField(
            model_name='cita',
            name='especialidad',
            field=models.CharField(choices=[('General', 'Medicina General'), ('Cirugía', 'Cirugía'), ('Dermatología', 'Dermatología'), ('Cardiología', 'Cardiología'), ('Oftalmología', 'Oftalmología'), ('Traumatología', 'Traumatología'), ('Odontología', 'Odontología')], default='General', max_length=30, verbose_name='Especialidad'),
        ),
        migrations.AddField(
            model_name='cita',
            name='nombre_paciente_temporal',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del Paciente (temporal)'),
        ),
        migrations.AddField(
            model_name='cita',
            name='nombre_tutor_temporal',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del Tutor (temporal)'),
        ),
        migrations.AddField(
            model_name='cita',
            name='sede',
            field=models.CharField(choices=[('Sede Bilbao', 'Sede Bilbao'), ('Sede Eliodoro Yáñez', 'Sede Eliodoro Yáñez'), ('Domicilio', 'Domicilio')], default='Sede Bilbao', max_length=30, verbose_name='Sede'),
        ),
        migrations.AlterField(
            model_name='atencionmedica',
            name='lugar_atencion',
            field=models.CharField(choices=[('Sede Bilbao', 'Sede Bilbao'), ('Sede Eliodoro Yáñez', 'Sede Eliodoro Yáñez'), ('Domicilio', 'Domicilio')], default='Sede Bilbao', max_length=30, verbose_name='Sede / Lugar'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='app.paciente'),
        ),
        migrations.AlterField(
            model_name='historicalatencionmedica',
            name='lugar_atencion',
            field=models.CharField(choices=[('Sede Bilbao', 'Sede Bilbao'), ('Sede Eliodoro Yáñez', 'Sede Eliodoro Yáñez'), ('Domicilio', 'Domicilio')], default='Sede Bilbao', max_length=30, verbose_name='Sede / Lugar'),
        ),
    ]
