# Generated by Django 5.2.5 on 2025-11-22 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_delete_diagnostico_cita_especialidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atencionmedica',
            name='tipo_especialidad',
            field=models.CharField(blank=True, help_text='Ej: Dermatología, Cirugía, Cardiología', max_length=100, null=True, verbose_name='Tipo de especialidad'),
        ),
        migrations.AddField(
            model_name='historicalatencionmedica',
            name='tipo_especialidad',
            field=models.CharField(blank=True, help_text='Ej: Dermatología, Cirugía, Cardiología', max_length=100, null=True, verbose_name='Tipo de especialidad'),
        ),
    ]
