# Generated by Django 5.2.5 on 2025-11-25 00:00

from django.db import migrations

INSUMOS_INICIALES = [
    # Medicamentos
    {"nombre": "Amoxicilina 500mg", "descripcion": "Antibiótico de amplio espectro", "costo": 2500.00},
    {"nombre": "Cefalexina 500mg", "descripcion": "Antibiótico cefalosporina", "costo": 3000.00},
    {"nombre": "Meloxicam 2mg/ml", "descripcion": "Antiinflamatorio no esteroideo", "costo": 4500.00},
    {"nombre": "Prednisona 5mg", "descripcion": "Corticosteroide", "costo": 1800.00},
    {"nombre": "Tramadol 50mg", "descripcion": "Analgésico opioide", "costo": 3500.00},
    {"nombre": "Metronidazol 250mg", "descripcion": "Antibiótico y antiparasitario", "costo": 2200.00},
    {"nombre": "Omeprazol 20mg", "descripcion": "Protector gástrico", "costo": 2800.00},
    
    # Material quirúrgico
    {"nombre": "Sutura absorbible 3-0", "descripcion": "Hilo quirúrgico reabsorbible", "costo": 5000.00},
    {"nombre": "Sutura no absorbible 2-0", "descripcion": "Hilo quirúrgico no reabsorbible", "costo": 4500.00},
    {"nombre": "Guantes quirúrgicos estériles", "descripcion": "Par de guantes talla M", "costo": 1500.00},
    {"nombre": "Gasas estériles", "descripcion": "Paquete de 10 unidades", "costo": 800.00},
    {"nombre": "Vendaje autoadhesivo", "descripcion": "Rollo de 5cm x 4.5m", "costo": 1200.00},
    {"nombre": "Jeringa 3ml", "descripcion": "Jeringa desechable con aguja", "costo": 500.00},
    {"nombre": "Jeringa 5ml", "descripcion": "Jeringa desechable con aguja", "costo": 600.00},
    {"nombre": "Jeringa 10ml", "descripcion": "Jeringa desechable con aguja", "costo": 700.00},
    {"nombre": "Catéter IV N°22", "descripcion": "Catéter intravenoso calibre 22", "costo": 2000.00},
    {"nombre": "Equipo de venoclisis", "descripcion": "Set completo para fluidoterapia", "costo": 3000.00},
    
    # Desinfectantes y antisépticos
    {"nombre": "Alcohol 70%", "descripcion": "Botella de 250ml", "costo": 800.00},
    {"nombre": "Clorhexidina 4%", "descripcion": "Solución antiséptica 250ml", "costo": 1500.00},
    {"nombre": "Yodopovidona", "descripcion": "Solución antiséptica 120ml", "costo": 1200.00},
    
    # Fluidos y soluciones
    {"nombre": "Suero fisiológico 0.9%", "descripcion": "Bolsa de 500ml", "costo": 2500.00},
    {"nombre": "Ringer Lactato", "descripcion": "Bolsa de 500ml", "costo": 2800.00},
    {"nombre": "Dextrosa 5%", "descripcion": "Bolsa de 500ml", "costo": 3000.00},
    
    # Material de diagnóstico
    {"nombre": "Portaobjetos", "descripcion": "Caja de 50 unidades", "costo": 1500.00},
    {"nombre": "Tubo EDTA", "descripcion": "Tubo para hemograma", "costo": 800.00},
    {"nombre": "Tubo con gel separador", "descripcion": "Tubo para bioquímica", "costo": 900.00},
]

def cargar_insumos(apps, schema_editor):
    Insumo = apps.get_model('app', 'Insumo')
    for insumo_data in INSUMOS_INICIALES:
        Insumo.objects.get_or_create(nombre=insumo_data['nombre'], defaults=insumo_data)

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_atencionmedica_tipo_especialidad_and_more'),
    ]

    operations = [
        migrations.RunPython(cargar_insumos),
    ]
