# Generated by Django 5.2.5 on 2025-11-25 00:00

from django.db import migrations

VACUNAS_INICIALES = [
    # Vacunas para Caninos
    {"nombre": "Sextuple Canina (DHPPI+L)", "especie_objetivo": "Canino", "dosis_necesarias": 3, "frecuencia_refuerzo_dias": 365},
    {"nombre": "Antirrábica Canina", "especie_objetivo": "Canino", "dosis_necesarias": 1, "frecuencia_refuerzo_dias": 365},
    {"nombre": "Quintuple Canina (DHPPI)", "especie_objetivo": "Canino", "dosis_necesarias": 3, "frecuencia_refuerzo_dias": 365},
    {"nombre": "Tos de las Perreras (Bordetella)", "especie_objetivo": "Canino", "dosis_necesarias": 1, "frecuencia_refuerzo_dias": 365},
    {"nombre": "Leptospirosis Canina", "especie_objetivo": "Canino", "dosis_necesarias": 2, "frecuencia_refuerzo_dias": 365},
    {"nombre": "Giardia Canina", "especie_objetivo": "Canino", "dosis_necesarias": 2, "frecuencia_refuerzo_dias": 365},
    
    # Vacunas para Felinos
    {"nombre": "Triple Felina (FVRCP)", "especie_objetivo": "Felino", "dosis_necesarias": 3, "frecuencia_refuerzo_dias": 365},
    {"nombre": "Antirrábica Felina", "especie_objetivo": "Felino", "dosis_necesarias": 1, "frecuencia_refuerzo_dias": 365},
    {"nombre": "Leucemia Felina (FeLV)", "especie_objetivo": "Felino", "dosis_necesarias": 2, "frecuencia_refuerzo_dias": 365},
    {"nombre": "Cuádruple Felina (FVRCP+FeLV)", "especie_objetivo": "Felino", "dosis_necesarias": 3, "frecuencia_refuerzo_dias": 365},
]

def cargar_vacunas(apps, schema_editor):
    Vacuna = apps.get_model('app', 'Vacuna')
    for vacuna_data in VACUNAS_INICIALES:
        Vacuna.objects.get_or_create(nombre=vacuna_data['nombre'], defaults=vacuna_data)

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_cargar_insumos_iniciales'),
    ]

    operations = [
        migrations.RunPython(cargar_vacunas),
    ]
