# Generated by Django 5.2.5 on 2025-11-27 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_cargar_vacunas_iniciales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='nombre_paciente_temporal',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del Paciente'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='nombre_tutor_temporal',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del Tutor'),
        ),
    ]
